return {
  -- Let's use LazyGit instead of Neogit
  -- {
  --   "NeogitOrg/neogit",
  --   dependencies = {
  --     "nvim-lua/plenary.nvim", -- required
  --     "nvim-telescope/telescope.nvim", -- optional
  --     "sindrets/diffview.nvim", -- optional
  --     "ibhagwan/fzf-lua", -- optional
  --   },
  --   opts = {
  --     sections = {
  --       recent = { folded = false },
  --     },
  --   },
  --   keys = {
  --     {
  --       "<leader>gg",
  --       function()
  --         require("neogit").open({ kind = "auto" })
  --       end,
  --       desc = "NeoGit",
  --     },
  --   },
  --   config = true,
  -- },
}
