return {
  -- add symbols-outline
  {
    "simrat39/symbols-outline.nvim",
    cmd = "SymbolsOutline",
    keys = { { "<leader>cs", "<cmd>SymbolsOutline<cr>", desc = "Symbols Outline" } },
    opts = {
      symbol_blacklist = {
        "File",
        "Module",
        -- "Namespace",
        -- "Package",
        -- "Class",
        -- "Method",
        "Property",
        -- "Field",
        -- "Constructor",
        -- "Enum",
        -- "Interface",
        -- "Function",
        "Variable",
        "Constant",
        "String",
        "Number",
        "Boolean",
        "Array",
        "Object",
        "Key",
        "Null",
        "EnumMember",
        "Struct",
        "Event",
        "Operator",
        "TypeParameter",
        "Component",
        "Fragment",
      },
    },
    config = true,
  },
}
